
# Jekyll config
auto: true
exclude:
  - CNAME
  - Makefile
  - README.md
lsi: false
pygments: true
safe: true
server: true

# Site details
lang: en-GB
host: rowanmanning.github.io/frag
tld: rowanmanning.github.io

# Repo details
repo:
  url: https://github.com/rowanmanning/frag
  raw: https://raw.github.com/rowanmanning/frag
  branch: master

# Author details
author:
  name: Rowan Manning
  url: http://rowanmanning.com/

# Tracking info
ga: UA-32567673-1
